INSERT INTO roles_ref (code, name, sys_name) VALUES (1, 'Администратор', 'admin') ON CONFLICT DO NOTHING;
INSERT INTO roles_ref (code, name, sys_name) VALUES (2, 'Сотрудник', 'employee') ON CONFLICT DO NOTHING;
INSERT INTO roles_ref (code, name, sys_name) VALUES (3, 'Менеджер', 'manager') ON CONFLICT DO NOTHING;
INSERT INTO roles_ref (code, name, sys_name) VALUES (4, 'Рекрутер', 'recruiter') ON CONFLICT DO NOTHING;

INSERT INTO vacancy_priorities_ref (code,value,is_archive) VALUES (1,'Низкий',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO vacancy_priorities_ref (code,value,is_archive) VALUES (2,'Средний',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO vacancy_priorities_ref (code,value,is_archive) VALUES (3,'Высокий',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO vacancy_priorities_ref (code,value,is_archive) VALUES (4,'Критический',FALSE) ON CONFLICT DO NOTHING;

INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (1,'Агинский Бурятский авт. округ',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (2,'Алтайский край',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (3,'Амурская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (4,'Архангельская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (5,'Астраханская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (6,'Белгородская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (7,'Брянская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (8,'Владимирская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (9,'Волгоградская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (10,'Вологодская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (11,'Воронежская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (12,'Еврейская авт. область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (13,'Ивановская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (14,'Иркутская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (15,'Кабардино-Балкарская Республика',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (16,'Калининградская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (17,'Калужская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (18,'Камчатская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (19,'Карачаево-Черкесская Республика',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (20,'Кемеровская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (21,'Кировская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (22,'Коми-Пермяцкий авт. округ',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (23,'Корякский авт. округ',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (24,'Костромская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (25,'Краснодарский край',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (26,'Красноярский край',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (27,'Курганская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (28,'Курская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (29,'Ленинградская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (30,'Липецкая область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (31,'Магаданская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (32,'Московская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (33,'Москва',32,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (34,'Мурманская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (35,'Ненецкий авт. округ',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (36,'Нижегородская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (37,'Новгородская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (38,'Новосибирская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (39,'Омская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (40,'Оренбургская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (41,'Орловская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (42,'Пензенская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (43,'Пермский край',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (44,'Приморский край',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (45,'Псковская оласть',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (46,'Республика Адыгея',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (47,'Республика Алтай',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (48,'Республика Башкортостан',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (49,'Республика Бурятия',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (50,'Республика Дагестан',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (51,'Республика Ингушетия',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (52,'Республика Калмыкия',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (53,'Республика Карелия',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (54,'Республика Коми',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (55,'Республика Крым',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (56,'Республика Марий Эл',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (57,'Республика Мордовия',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (58,'Республика Саха-Якутия',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (59,'Республика Северная Осетия-Алания',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (60,'Республика Татарстан',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (61,'Республика Тыва',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (62,'Республика Хакасия',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (63,'Республика Чечня',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (64,'Ростовская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (65,'Рязанская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (66,'Самарская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (67,'Санкт-Петербург',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (68,'Саратовская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (69,'Сахалинская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (70,'Свердловская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (71,'Смоленская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (72,'Ставропольский край',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (73,'Таймырский авт. округ',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (74,'Тамбовская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (75,'Тверская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (76,'Томская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (77,'Тульская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (78,'Тюменская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (79,'Удмуртская Республика',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (80,'Ульяновская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (81,'Усть-Ордынский Бурятский авт. окр.',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (82,'Хабаровский край',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (83,'Ханты-Мансийский авт. округ - Югра',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (84,'Челябинская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (85,'Чеченская республика',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (86,'Читинская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (87,'Чувашская Республика — Чувашия',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (88,'Чукотский авт. округ',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (89,'Эвенкийский авт. округ',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (90,'Ямало-Ненецкий авт. округ',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (91,'Ярославская область',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (92,'Севастополь',55,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (93,'Нижний Новгород',36,FALSE) ON CONFLICT DO NOTHING;

INSERT INTO countries_ref (code,value,is_archive) VALUES (1,'Российская Федерация',FALSE) ON CONFLICT DO NOTHING;

INSERT INTO family_stats_ref (code,value,is_archive) VALUES (1,'Single',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO family_stats_ref (code,value,is_archive) VALUES (2,'Married',FALSE) ON CONFLICT DO NOTHING;

INSERT INTO contact_types_ref (code,value,is_archive) VALUES (1,'Мобильный телефон',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO contact_types_ref (code,value,is_archive) VALUES (2,'Домашний телефон',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO contact_types_ref (code,value,is_archive) VALUES (3,'Email',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO contact_types_ref (code,value,is_archive) VALUES (4,'Telegram',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO contact_types_ref (code,value,is_archive) VALUES (5,'WhatsApp',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO contact_types_ref (code,value,is_archive) VALUES (6,'Viber',FALSE) ON CONFLICT DO NOTHING;

INSERT INTO languages_ref (code,value,is_archive) VALUES (1,'Русский',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO languages_ref (code,value,is_archive) VALUES (2,'Английский',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO languages_ref (code,value,is_archive) VALUES (3,'Немецкий',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO languages_ref (code,value,is_archive) VALUES (4,'Испанский',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO languages_ref (code,value,is_archive) VALUES (5,'Китайский',FALSE) ON CONFLICT DO NOTHING;

INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (1,'A1','Начальный',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (2,'A2','Ниже среднего',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (3,'B1','Средний',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (4,'B2','Выше среднего',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (5,'C1','Продвинутый',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (6,'C2','Профессиональный',FALSE) ON CONFLICT DO NOTHING;

INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (1,'Новый',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (2,'В работе',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (3,'Завершен',NULL,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (4,'HR собеседование',2,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (5,'Техническое собеседование',2,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (6,'Принятие решения',2,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (7,'Оффер',2,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (8,'Отказ кандидата',3,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (9,'Отказ компании',3,FALSE) ON CONFLICT DO NOTHING;
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (10,'Оффер принят',3,FALSE) ON CONFLICT DO NOTHING;

INSERT INTO vacancy_stats_ref (code,value,is_archive) VALUES (1,'Заявка',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO vacancy_stats_ref (code,value,is_archive) VALUES (2,'В работе',FALSE) ON CONFLICT DO NOTHING;
INSERT INTO vacancy_stats_ref (code,value,is_archive) VALUES (3,'Завершено',FALSE) ON CONFLICT DO NOTHING;
