INSERT INTO roles_ref (code, name, sys_name) VALUES (1, 'Администратор', 'admin') ON CONFLICT DO NOTHING;
INSERT INTO roles_ref (code, name, sys_name) VALUES (2, 'Сотрудник', 'employee') ON CONFLICT DO NOTHING;
INSERT INTO roles_ref (code, name, sys_name) VALUES (3, 'Менеджер', 'manager') ON CONFLICT DO NOTHING;
INSERT INTO roles_ref (code, name, sys_name) VALUES (4, 'Рекрутер', 'recruiter') ON CONFLICT DO NOTHING;

INSERT INTO vacancy_priorities_ref (code,value,is_archive) VALUES (1,'Низкий',FALSE);
INSERT INTO vacancy_priorities_ref (code,value,is_archive) VALUES (2,'Средний',FALSE);
INSERT INTO vacancy_priorities_ref (code,value,is_archive) VALUES (3,'Высокий',FALSE);
INSERT INTO vacancy_priorities_ref (code,value,is_archive) VALUES (4,'Критический',FALSE);

INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (1,'Агинский Бурятский авт. округ',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (2,'Алтайский край',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (3,'Амурская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (4,'Архангельская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (5,'Астраханская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (6,'Белгородская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (7,'Брянская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (8,'Владимирская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (9,'Волгоградская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (10,'Вологодская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (11,'Воронежская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (12,'Еврейская авт. область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (13,'Ивановская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (14,'Иркутская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (15,'Кабардино-Балкарская Республика',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (16,'Калининградская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (17,'Калужская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (18,'Камчатская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (19,'Карачаево-Черкесская Республика',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (20,'Кемеровская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (21,'Кировская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (22,'Коми-Пермяцкий авт. округ',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (23,'Корякский авт. округ',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (24,'Костромская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (25,'Краснодарский край',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (26,'Красноярский край',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (27,'Курганская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (28,'Курская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (29,'Ленинградская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (30,'Липецкая область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (31,'Магаданская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (32,'Московская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (33,'Москва',32,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (34,'Мурманская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (35,'Ненецкий авт. округ',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (36,'Нижегородская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (37,'Новгородская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (38,'Новосибирская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (39,'Омская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (40,'Оренбургская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (41,'Орловская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (42,'Пензенская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (43,'Пермский край',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (44,'Приморский край',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (45,'Псковская оласть',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (46,'Республика Адыгея',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (47,'Республика Алтай',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (48,'Республика Башкортостан',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (49,'Республика Бурятия',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (50,'Республика Дагестан',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (51,'Республика Ингушетия',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (52,'Республика Калмыкия',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (53,'Республика Карелия',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (54,'Республика Коми',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (55,'Республика Крым',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (56,'Республика Марий Эл',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (57,'Республика Мордовия',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (58,'Республика Саха-Якутия',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (59,'Республика Северная Осетия-Алания',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (60,'Республика Татарстан',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (61,'Республика Тыва',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (62,'Республика Хакасия',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (63,'Республика Чечня',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (64,'Ростовская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (65,'Рязанская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (66,'Самарская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (67,'Санкт-Петербург',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (68,'Саратовская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (69,'Сахалинская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (70,'Свердловская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (71,'Смоленская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (72,'Ставропольский край',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (73,'Таймырский авт. округ',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (74,'Тамбовская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (75,'Тверская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (76,'Томская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (77,'Тульская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (78,'Тюменская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (79,'Удмуртская Республика',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (80,'Ульяновская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (81,'Усть-Ордынский Бурятский авт. окр.',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (82,'Хабаровский край',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (83,'Ханты-Мансийский авт. округ - Югра',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (84,'Челябинская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (85,'Чеченская республика',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (86,'Читинская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (87,'Чувашская Республика — Чувашия',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (88,'Чукотский авт. округ',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (89,'Эвенкийский авт. округ',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (90,'Ямало-Ненецкий авт. округ',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (91,'Ярославская область',NULL,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (92,'Севастополь',55,FALSE);
INSERT INTO adresses_ref (code,value,parent_id,is_archive) VALUES (93,'Нижний Новгород',36,FALSE);

INSERT INTO countries_ref (code,value,is_archive) VALUES (1,'Российская Федерация',FALSE);

INSERT INTO family_stats_ref (code,value,is_archive) VALUES (1,'Single',FALSE);
INSERT INTO family_stats_ref (code,value,is_archive) VALUES (2,'Married',FALSE);

INSERT INTO contact_types_ref (code,value,is_archive) VALUES (1,'Мобильный телефон',FALSE);
INSERT INTO contact_types_ref (code,value,is_archive) VALUES (2,'Домашний телефон',FALSE);
INSERT INTO contact_types_ref (code,value,is_archive) VALUES (3,'Email',FALSE);
INSERT INTO contact_types_ref (code,value,is_archive) VALUES (4,'Telegram',FALSE);
INSERT INTO contact_types_ref (code,value,is_archive) VALUES (5,'WatsApp',FALSE);
INSERT INTO contact_types_ref (code,value,is_archive) VALUES (6,'Viber',FALSE);

INSERT INTO languages_ref (code,value,is_archive) VALUES (1,'Русский',FALSE);
INSERT INTO languages_ref (code,value,is_archive) VALUES (2,'Английский',FALSE);
INSERT INTO languages_ref (code,value,is_archive) VALUES (3,'Немецкий',FALSE);
INSERT INTO languages_ref (code,value,is_archive) VALUES (4,'Испанский',FALSE);
INSERT INTO languages_ref (code,value,is_archive) VALUES (5,'Китайский',FALSE);

INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (1,'A1','Начальный',FALSE);
INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (2,'A2','Ниже среднего',FALSE);
INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (3,'B1','Средний',FALSE);
INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (4,'B2','Выше среднего',FALSE);
INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (5,'C1','Продвинутый',FALSE);
INSERT INTO language_levels_ref (code,level_code,value,is_archive) VALUES (6,'C2','Профессиональный',FALSE);

INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (1,'В работе',NULL,FALSE);
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (2,'Завершен',NULL,FALSE);
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (3,'Новый',NULL,FALSE);
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (4,'HR собеседование',1,FALSE);
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (5,'Техническое собеседование',1,FALSE);
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (6,'Тестовое задание',1,FALSE);
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (7,'Принятие решения',1,FALSE);
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (8,'Оффер',1,FALSE);
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (9,'Отказ кандидата',1,FALSE);
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (10,'Отказ компании',2,FALSE);
INSERT INTO interview_stages_ref (code,value,parent_id,is_archive) VALUES (11,'Оффер принят',2,FALSE);

INSERT INTO vacancy_stats_ref (code,value,is_archive) VALUES (1,'Заявка',FALSE);
INSERT INTO vacancy_stats_ref (code,value,is_archive) VALUES (2,'В работе',FALSE);
INSERT INTO vacancy_stats_ref (code,value,is_archive) VALUES (3,'Завершено',FALSE);
